### ISSUE TITLE
How do I deploy the refactored visualization html?

### ISSUE THREAD

**Issue by Firedrops** [allenday/nanostream-dataflow#22]
I noticed that the `<scripts>` sections have been removed from the sunburst.html `<body>`, and placed into their own folder and scripts.

So when deployed, this website is now empty https://nano-stream1.appspot.com/

Previously, my app.yaml was

```
service: default

runtime: python37

handlers:
- url: /
  static_files: sunburst.html
  upload: sunburst.html

- url: /(.*)
  static_files: /\1
  upload: /(.*)
```

Should this be changed to correctly reference where the scripts are now? Or is the solution elsewhere?

**Comment by obsh** [comment]
I've tried following configuration, and it worked for me:

```
service: default

runtime: python37

handlers:
- url: /
  static_files: sunburst.html
  upload: sunburst.html

- url: /scripts/(.*)
  static_files: scripts/\1
  upload: scripts/(.*)

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)
```
